version: "3.2"
services:
  php:
    container_name: limesurvey-php-fpm
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
       LIMESURVEY_ADMIN_USER_NAME: ${LIMESURVEY_ADMIN_USER_NAME}
       LIMESURVEY_ADMIN_USER_PASSWORD: ${LIMESURVEY_ADMIN_USER_PASSWORD}
       LIMESURVEY_ADMIN_FULL_NAME: ${LIMESURVEY_ADMIN_FULL_NAME}
       LIMESURVEY_ADMIN_EMAIL: ${LIMESURVEY_ADMIN_EMAIL}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
  apache:
    container_name: limesurvey-apache-webserver
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "${DB_PORT_IN}:${DB_PORT_OUT}"
    volumes:
      - data:/var/lib/mysql/
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_TCP_PORT: ${DB_PORT_OUT}
    container_name: limesurvey-mysql-database
networks:
  frontend:
  backend:
volumes:
    data:
